image: "harbor.choilab.xyz/fastapi-demo:0.0.1"

resources:
  requests:
    cpu: "0.1m"
    memory: "128Mi"
  limits:
    cpu: "0.1m"
    memory: "128Mi"

ingress:
  enabled: false
  host: example1.choilab.xyz
