replicaCount: 1

image:
  repository: choisunguk/lettuce-connection
  tag: "latest"

env:
- name: REDIS_HOST
  value: "redis-redis-cluster.default.svc.cluster.local"
- name: REDIS_PORT
  value: "6379"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi

livenessProbe: {}

readinessProbe: {}

service:
  type: ClusterIP
  port: 80
  nodePort: 32101
